<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

Two ways to create own function

1. Named
2. Anonymous

### 1.1 Named functions that return

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [2]:
greeting("Super Man")

'Hello Super Man!'

In [3]:
greeting(name="Super Man")

'Hello Super Man!'

Function name is called greeting() --> accepts a single argument "name"

Keywords: 
1. def
2. colon (:)
3. indentation that demarcates the function’s code block 

return: python jumps out of the function with the return value => pick up the returned value by assigning it to a variable or 

**can only use within a function**

In [4]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [5]:
print(greeting(name='Super Man'))

Hello Super Man!


In [9]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()


In [10]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

Some function does not return anything (e.g. print)

### 1.3 Anonymous functions

also called lambda functions

In [11]:
my_short_function = lambda name: f"Hello {name}!"

In [12]:
my_short_function(name="Super Man")

'Hello Super Man!'

lamda returns value of **LAST** statement

In [13]:
#sort 2D list using "sorted()" 

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [17]:
#to sort by other criteria, key to be used for comparison must be specified

sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [18]:
#to sort by 3rd key

sorted(numbers, key=lambda x: x[2])     

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [19]:
#SUPER USEFUL

#can even sort based on sum of elements

sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

TO make arguments to our function optional, give argument default value

In [20]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [21]:
#able to run without argument

greeting()

'Hello no one!'

**ANOTHER EXAMPLE**

In [23]:
?print 

#print() can accept other arguments and are optional with default values

In [24]:
#but we can specify 


print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

Abstraction of detail => hide unnecessary details atm

### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [30]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'



***Python would run f'Hello {name}!' normally, the moment if condition not met. Else is unecessary***




In [ ]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    if name == ''
    return f'Hello {name}!'

In [34]:
fruits = ['mango', 'apple', 'cherry']

def fruity(fruit):
    if 'mango' in fruit:
        print('yay')
    elif 'apple' in fruits:
        print('yayyay')
    else:
        print('nay')
        
fruity(fruits)

yay


## Exercise 2 :  Calculator functions

In [2]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [5]:
def add(x,y):
    return x + y
add(x,y)

array([100, 100, 100, 100, 100])

In [13]:
def subtract(x,y):
    return x - y
subtract(x,y)

array([-28, -32, -12,  52,  27])

In [12]:
def multiply(x,y):
    return x * y
multiply(x,y)

array([2304, 2244, 2464, 1824,    0])

In [18]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def divide(x,y):

    if y == 0 :
        return 'error'
    return x / y

print(divide(x,y))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [15]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])

def divide(x,y): 
    for p in y:
        if p == 0 :
            return 'error'
    return x / y
    
print(divide(x,y))
    
  




error


In [3]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def divide(x,y): 
    for p in y:
        if p == 0 :
            return 'error'
    return x / y
    
print(divide(x,y))

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [1]:
def max_info(numbers):
    if type(numbers) == list:
        max_number = np.max(numbers)    # return max
        max_index = np.argmax(numbers)  #return index
        return max_number, max_index

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]    

In [25]:
max_info(numbers)

(83, 2)