<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [2]:
# assert : CHECKS A CONDITION, HALTS EXECUTION IF NECESSARY, PRINT 

#stops the flow IF CONDITION FAILS

#e.g.
#assert condition-to-check, message

In [7]:
x = 10      
assert x >= 0, "x is becoming negative!"

#programme runs as long as long as condition is true

In [5]:
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [ ]:
# try-except : catch and handle exceptions 

In [ ]:
# input : solicit user response

In [8]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.99
The square of 99 is 9801!


In [10]:
# but what if input is not a number (e.g. 'hahaha')

try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.78h
Oh oh! I cannot square 78h!


In [11]:
#if smt goes wrong, python ignores error, runs code in the except block

## 2 Some loose ends

Three ways to pass a value to an argument
1) Positional
2) Keyword
3) Default

### 2.1 Positional, keyword and default arguments

In [17]:
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121


121

In [18]:
#DOES NOT WORK

funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional

SyntaxError: positional argument follows keyword argument (1521717268.py, line 3)

In [22]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c       #assign 1,2,3 to a,b,c
                                  #using positional order of arguments

In [24]:
funny_add(2,3,4)

432

In [14]:
#another way: explicitly specify keyword to assign values
#by calling function as funny_add(c=3, b=1, a=2)

### 2.2 Docstrings

In [26]:

# docstring : allow to document what function does inside the function
# NEEDS TO BE SANDWICHED BETWEEN PAIR OF ' ' ' OR " " "
#shown when we ask help()

In [25]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

In [27]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



In [ ]:
# docstrings CAN be used for writing multiline comments

### 2.3 Function are first class citizens

In [ ]:

# Python allows us to PASS A FUNCTION AS AN ARGUMENT TO ANOTHER FUNTION

In [32]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        

1.0

In [30]:
my_function(np.pi/2, np.cos) 

6.123233995736766e-17

In [31]:
my_function(np.pi/2, lambda x: np.cos(2*x)) 

-1.0

In [ ]:
# WHEN WE PASS FUNCTION AS AN ARGUMENT => DO NOT INCLUDE ()

### 2.4 More unpacking

In [29]:

# UNPACKING CAN MAKE EXTRACTING INFORMATIONS FROM LIST AND ARRAYS EASY


In [33]:
#EXAMPLE 1

x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [34]:
#EXAMPLE 2

x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [35]:
#EXAMPLE 3 (*y)

x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [36]:
#EXAMPLE 4 (*_)

x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [44]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [39]:
def add(x,y):
    return x + y
print (add(x,y))

6


In [38]:
def subtract(x,y):
    return x - y
print (subtract(x,y))

-4


In [68]:
def multiply(x,y):
    return x * y
multiply(x,y)

array([2304, 2244, 2464, 1824,    0])

In [79]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])

def divide(x,y):
    for value in y:
        assert value != 0,'error'
    return x / y

divide(x,y)

AssertionError: error

## Exercise 2 :  A better calculator II

In [72]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [88]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])

def divide(x,y):
    
    try:
        for value in y:
            assert value != 0
        return x / y
    
    except: 
        print('error')

divide(x,y)

error


In [92]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, "9"])

def divide(x,y):
    
    try:
        for value in y != 0:
            return x / y
    
    except: 
        print('error')

divide(x,y)

error


/var/folders/fv/h6xblgrj2k1d0g0kcf67r8xh0000gn/T/ipykernel_5823/2945152992.py:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  for value in y != 0:


In [98]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def divide(x,y):
    
    for value in y:
        try:
            value != 0
            print(x / y)
        except:
            print('error')
        
divide(x,y)

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
