<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:
# SUBSETTING ==> selecting a subset of data in the list

# INDEXING ==> selecting one element

# SLICING ==> selecting a range of elements

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [2]:
# Slicing gives us a range of elements ==> need specify two indices to indicate start and end

# Slicing with [i:j] ==> slice will start at i and end at j-1 ==> total of j-i elements.

### 1.2 Subsetting by masking (Arrays only)

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)


[False False False  True  True  True  True  True  True  True]


In [6]:
#to show only those that are true => subset by MASKING ==> ONLY FOR ARRAY

np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
#alternative, without creating another variable

np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
# MORE EXAMPLES

np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [12]:
py_list_2d[3]        # What is at position 4 (index 3)?

#recall 2d ==> both items in element

[4, 'D']

In [13]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

#second [] signifies which element in particular position

4

In [14]:
#TEST

py_list_2d[6][1] # should give me G

'G'

In [17]:
py_list_2d[:3]  # positions 1 to 3 (index 0 to 2)

[[1, 'A'], [2, 'B'], [3, 'C']]

In [28]:
py_list_2d[:3][0]  # positions 1 to 3 // THEN AFTERWARDS first 2d 

#NOTE diff btwn list & array

[1, 'A']

In [21]:
#TEST

py_list_2d[3]

[4, 'D']

In [31]:
#TEST
py_list_2d[3][1]   # only when one 2d item appears ==> then is within it second element

'D'

### 1.4 Indexing & Slicing 2D Arrays

In [24]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])


In [26]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U21')

In [27]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

#NOTE the diff bwn list & array ==> syntax for arrays uses just a single pair of square brackets ([ ]).

'4'

In [29]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [30]:
np_array_2d[:3, 0]

#DIFFERENT FROM LIST ==> array chooses first element of each index

array(['1', '2', '3'], dtype='<U21')

In [32]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [33]:
np_array_2d[:, 0]    # ":" means EVERYTHING

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

### 1.5 Growing lists

In [34]:

x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [37]:
x=[1]
x= x + [2]        #Appending one element at a time.
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [39]:
x=[1]
x+= [2]         #can also do this
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [40]:
x=[1]            #to append multiple elements in one go
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [42]:
x=[1]                 #to pre-pend stuff.
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [43]:
# HIDDEN FUNCTION append()

x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [ ]:

# Tuples vs List ==> tuple use ( ) and cannot be changed after creation.


In [2]:
a=(1, 2, 3)     # Define tuple

In [45]:
print(a[0])    # Access data

1


In [5]:
# The following will NOT work ==> cannot change the data.

a[0] -= 1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!    

#recall that this is merely assigning another name


In [48]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

#need to clone a seperate set

## Exercise 1 :  Total recall?

Subsetting : selecting a subset of data 

Indexing : selecting a single element

Slicing : selecting a range of elements

Masking : showing only the parts you want (cover the rest)

## Exercise 2 :  Show me the ‘odd’ letters

In [49]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


In [70]:
np_array_2d[:,0].astype(int)%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [71]:
mask = np_array_2d[:,0].astype(int)%2 == 1

mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [73]:
np_array_2d[mask , 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')