<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:
# SUBSETTING ==> selecting a subset of data in the list

# INDEXING ==> selecting one element

# SLICING ==> selecting a range of elements

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [2]:
# Slicing gives us a range of elements ==> need specify two indices to indicate start and end

# Slicing with [i:j] ==> slice will start at i and end at j-1 ==> total of j-i elements.

### 1.2 Subsetting by masking (Arrays only)

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)


[False False False  True  True  True  True  True  True  True]


In [6]:
#to show only those that are true => subset by MASKING ==> ONLY FOR ARRAY

np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
#alternative, without creating another variable

np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
# MORE EXAMPLES

np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [ ]:

# Your code here


In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [12]:
py_list_2d[3]        # What is at position 4 (index 3)?

#recall 2d ==> both items in element

[4, 'D']

In [13]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

#second [] signifies which element in particular position

4

In [14]:
#TEST

py_list_2d[6][1] # should give me G

'G'

In [17]:
py_list_2d[:3]  # positions 1 to 3 (index 0 to 2)

[[1, 'A'], [2, 'B'], [3, 'C']]

In [18]:
py_list_2d[:3][0]  # positions 1 to  // THEN AFTERWARDS first 2d 

[1, 'A']

In [21]:
#TEST

py_list_2d[3]

[4, 'D']

In [22]:
py_list_2d[3][1]   # only when one 2d item appears ==> then is within it second element

'D'

### 1.4 Indexing & Slicing 2D Arrays

In [ ]:

# Your code here


### 1.5 Growing lists

In [ ]:

# Your code here


## 2 Some loose ends

### 2.1 Tuples

In [ ]:

# Your code here


### 2.2 Be VERY careful when copying

In [ ]:

# Your code here


## Exercise 1 :  Total recall?

In [ ]:



# Your solution here




## Exercise 2 :  Show me the ‘odd’ letters

In [ ]:



# Your solution here


