<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [6]:
import numpy as np

In [8]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]     

#Dictionaries use a key and an associated value separated by a :

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [5]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [9]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [11]:
print(py_real_names[0])  #counting starts at 0

Natasha Romanoff


In [12]:
print(py_super_names[0])

Black Widow


In [14]:
#USING INDEX "-1" GIVES US LAST ELEMENT
print(py_super_names[2])

Doctor Strange


In [16]:
print(py_real_names[-1])   #known as reverse indexing

Stephen Strange


### 1.3 Accessing data from a dictionary

In [17]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [19]:
print(superhero_info["Natasha Romanoff"])   #key-value structure

Black Widow


In [20]:
#To access all keys

superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [21]:
#To access all values

superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [23]:
# 2D list 

py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [29]:
print(superhero_info["Tony Stark"])

Iron Man


## 2 Lists vs. Arrays

### 2.1 Size

In [30]:
#setup

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [32]:
#to find out how many elements in the list "len()"

len(py_list_2d)

10

In [33]:
len(np_array_2d)

10

In [34]:
np_array_2d.shape  #shape is not a function -> no need brackets
#2 stands for 2D => number of items in the bracket

(10, 2)

### 2.2 Arrays are fussy about type

In [36]:
py_list = [1, 1.5, 'A']    #np arrays ==> likes having a single data type
np.array(py_list)          #numbers converted to english

#can solve by changing type (typecast) using the ‘hidden’ function astypes()

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [38]:
pr_list + 10

NameError: name 'pr_list' is not defined

In [40]:
np_array + 10    #add 10 to each values

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [41]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]     #setup of lists

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [42]:
#py_list ==> combining of list

py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [44]:
#np_array ==> adding values tgt

np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [46]:
#py_list*2 ==> add again the same sequence into the list

#makes a list grow

py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [50]:
#np_array82 ==> multiply 2 to existing values

#multiply its elements by its number

np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [51]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)


In [52]:
#py_list cannot square

py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [53]:
#np_array can square

np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [54]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [56]:
py_list == 3   #list ==> question is simi?

False

In [58]:
py_list > 3    #list ==> does not work

TypeError: '>' not supported between instances of 'list' and 'int'

In [59]:
np_array == 3   #array checks through each element 

array([False, False,  True, False, False])

In [61]:
np_array > 3    #array checks through each element 

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [62]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         



In [78]:
#PY_LIST

#sum, max, min  ==> why no mean?

#OPERATION WORKS ON WHOLE LIST

In [71]:
sum(py_list)     # sum() is a base Python function

15

In [ ]:
max(py_list)     # max() is a base Python function

In [69]:
min(py_list)     # min() is a base Python function

1

In [68]:
py_list.sum()  #does not work, sum issa function in front?

AttributeError: 'list' object has no attribute 'sum'

In [79]:
#NP_ARRAY  ==> function put behind

#sum, mean. max, min

#OPERATION WORKS ON INDIVIDUAL ELEMENTS OF ARRAY


In [72]:
np_array.sum()

15

In [74]:
np_array.mean()

3.0

In [75]:
np_array.max()

5

In [76]:
np_array.min()

1

## Exercise 1 :  Total recall?

Two similarities
1. input of elements 
2. both able to find sum, max, min

Two differences
1. py_list unable to calculate mean
2. np_array function is at the back, while py_list function is in the front
 
What is a dictionary
1. input key to find value

## Exercise 2 :  Index me

In [87]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

print(py_list[0])   # Prints 'a1'
    
print(py_list[2])   # Prints 'c3'
        
print(py_list[4])   # Prints 'e5'
            
print(py_list[6])   # Prints 'g7'

print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [89]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()

superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()



In [98]:
print(superhero_info["Natasha Romanoff"])

BLACK WIDOW


In [100]:
print(superhero_info["Tony Stark"])

IRON MAN


## Exercise 4 :  How many ones

In [108]:
numbers = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

x = np.array(numbers)


x == 1

sum(x==1)    # False is considered 0, and True is considered 1 by sum().


9

In [110]:
(x ==1).sum()

9